## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "dogeplusplus"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/okami_doge.png"
  favicon = true

[Params.social]
  github = "https://github.com/dogeplusplus"
  email = "albertswchung@gmail.com"
  linkedin = "https://www.linkedin.com/in/albert-chung-a9b549104/"
